apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-manifests
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/waaghals/cluster-management.git
    targetRevision: main
    path: 'loki/manifests'
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
