apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  generators:
    - clusters: {} # All clusters
  template:
    metadata:
      name: prometheus-operator-{{name}}
    spec:
      project: monitoring
      source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        # keep this value in sync with the chart value in prometheus-operator-crd
        targetRevision: 35.3.0
        helm:
          skipCrds: true
          # Disable alertmanager as we do not use it
          # Disable grafana as it is only needed in the management cluster
          values: |
            nameOverride: prometheus
            fullnameOverride: prometheus
            grafana:
              enabled: false
            alertmanager:
              enabled: false
            prometheus:
              ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                  - prometheus.{{name}}.waaghals.dev
                tls:
                  - secretName: prometheus-cert
                    hosts:
                      - prometheus.{{name}}.waaghals.dev
              prometheusSpec:
                serviceMonitorSelectorNilUsesHelmValues: false
                podMonitorSelectorNilUsesHelmValues: false
                probeSelectorNilUsesHelmValues: false
                ruleSelectorNilUsesHelmValues: false
                remoteWrite:
                  - url: https://mimir.management.waaghals.dev/api/v1/push                       
                    basicAuth:
                      username:
                        key: username
                        name: mimir-credentials
                      password:
                        key: password
                        name: mimir-credentials
                    writeRelabelConfigs:
                      - targetLabel: cluster
                        replacement: {{name}}
      destination:
        server: '{{server}}'
        namespace: prometheus-operator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
