apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns
resources:
  - gcloud-credentials.yaml

patchesStrategicMerge:
  - patch-configmap.yaml

configMapGenerator:
  - name: grafana-dashboard
    files:
      - dashboard.json

generatorOptions:
  disableNameSuffixHash: true
