apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-manifests
  namespace: argocd
spec:
  generators:
    - clusters: {} # All clusters
  template:
    metadata:
      name: linkerd-manifests-{{name}}
    spec:
      project: service-mesh
      source:
        repoURL: https://github.com/waaghals/cluster-management.git
        targetRevision: main
        path: 'linkerd/manifests'
        plugin:
          name: argocd-vault-plugin
      destination:
        server: '{{server}}'
        namespace: 'linkerd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true