apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: loki-credentials
  namespace: fluent-bit
spec:
  encryptedData:
    password: AgAgOYVO/RK4Tdvbag3YysGF586tninvXAABDTuJBs96Fif0m33me3GU0Udt4R8uSIBtvijweaVMpADqCkbmgvcVWRBOkIKzxvgIwYCjnkchnpFlJ9AIN5M9rxrOeF9LFVpAyluMMgvyzI7na0I2oGRUWcA3UPFfZQMqHzFojce5ty7OWnsD9e37jfY5gdjC2+TfKOLnYdP7aSUqoqXzNr/k2d7tRONTyQu1RmRe/mPuKGkBkIzEnZCHHnmgSyub3wklPaf26+OVZI8W4iBaL1+jOXFVMiZOyqL10Ar9L0l0kKLCUjFn6ONSY1Trsr72xidf5urNOW0kqFyD8me6C0/g5zd3jnygg1RBOKCedUSZUo4lb5L4hW+1urHMQGVG1M499siNRjDskagxzR76wjRgxh4470fuB/5hS6MZ0JpodI2dZTnw8UXJu3CMTv79rdlB2b0afl3mHxhaPlJ2DZA1o+D+RfU9reR6Ld/UEbeMLLnzPE9WGa+R6v9QoeJbVT+NELIQKN3LVAWEIqpLezzuGNSAQ9GLssfAAJx1RwTpOl9GoZ50dcN50/bdpo0uXUT0NOQJ8qT/15zUydgiDFo0lW8PVW97IuTRwnnUJAsB1hlZYFbIgCv+2mzZAuT6gFucbEDbMufksXr+M5mvLULm1+6Y28Ypc+NPERlucPIL4o0tFhVyfZHSgyAJt8VD8qC//oZAI+v3RBEkD9Es/Ea5wltuhgFS8XI=
    username: AgArb0APpoPt0VhZ2un6BItWOab8xSxM3l7cySC2G15KdTQZ5zO1V7fVEfZGXhhOWB+uvaDnyEy7AIZcCHPzpCL7vQiovrpCcJzN5dKnXx6pfiZ7z7nMnkMTQlGu4PEIkEaw+89/RbBHmdEnxIz8L2vHrcLLEWKztE3sZdUB07B5N3l6HVt/Yst2UdbbMyfIM++zUvAMQCEvb+18yhYSZ2TaUwfsRhJMaBA1imOyAfLMd2qkE96g03bYZl9Al9HeGTBmL7ywsiXjxyZb2/p2pHWTg7e0d0M76ZT4uudhTkkqVJFRK1sT9hycYx9YMNdha0DATaM5bkSNIKEALEkpAXXYEKtglTNIwwdijQZ4Yby0Z6SYkwZzykPhGZ14/SOrRYOUDlnXu4jbTle73yQ2Z1n8eEritYmK/EivfIp8cnQkH7Qhbrjulq//UnQMVIBYK0TMpvrpIhC/XvJeDdei1aD/Z9SyegdLnK0qZy5SMy+xUFzbpC6pyMeDKEpP0Y+wWvSrK55bX5AEkd39PmOf0H5E+fNu9FlGpCzziByvKXxvhPFrvigCe/TuetJvezgmc2klHEodlorUnkB0ruWg+4xKFP1mg6UQIMo4hbdTP82yGoeXW+JPgDF/YAVggdEEkVsoLRwfo8XBiCi3uPyhzv93vKX3oaeQksna3s1mvjYpMsmzrHiLpWY07Gi5EcSSFqICkdHv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: loki-credentials
      namespace: fluent-bit
