piVersion: multik8s.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: multik8s-cluster-virtual
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  compositionSelector:
    matchLabels:
      provider: virtual
  id: worker-beta
  parameters:
    nodes:
      count: 3
      size: small
    networkRef:
      id: multik8s-cluster-aws
  writeConnectionSecretToRef:
    name: worker-beta
