apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - clusters: {} # All clusters
  template:
    metadata:
      name: sealed-secrets-{{name}}
    spec:
      project: security
      source:
        chart: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.6.4
        helm:
          values: |
            metrics:
              serviceMonitor:
                enabled: false # true
            namespaceOverride: sealed-secrets
      destination:
        server: '{{server}}'
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
