apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
resources:
  - certificate/selfsigned-ca.yaml
  - issuer/selfsigned.yaml
  - cluster-issuer/ca.yaml
  - cluster-issuer/letsencrypt.yaml
  - secret/glcoud.yaml

patchesStrategicMerge:
  - patch-configmap.yaml

configMapGenerator:
  - name: grafana-dashboard
    files:
      - dashboard.json

generatorOptions:
  disableNameSuffixHash: true
