apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: loki-credentials
  namespace: loki
spec:
  encryptedData:
    .htpasswd: AgA/FXxBROiq7RWvZZZujarjgStVYZILULfBGWxtmO2BPJ+/Ih+Tyfe+1v2DSL07FhZ2CXkDm1O7SPR3ZWZb8sLWToa9c4d6RImrgMGmC5d/I9UazlahvQOcQZSbT58FCG73onWbx2tva4+EwY0bmNreToozNoJWAxPSwg9CkQODx66Ltb9Dksu6MoaGQVh5OqrBYOJs7d8GMpvN6LEjrfOZa8yi/WddToWoxkEuoNOoEHzEzhELnCq2FFBBkk5jfuE9wlf7BKw6TRF3xgGGrZVeRUvDkngyh+z4JtTAiIFZsmGfJ9P4Sux7YAngtgfpvXoMizW8hsyVOnY3lG6zG6EVjrKsIUXlSWaRHZHQ29lDbw+Jiz78TmAZD1JkaWRHl279CSGgsHNDJs2e3oITh3M+i4Qxz4F05E2ZPBAP/5746pamBXpoXx1tWJVj0ZE/RUi8TV2vp5LrBcSkuhg9Af/sqoYf7cXRVDf8TLwgSocA+x0DsbJbR0wFUeIHb0+5+RZ5JM09Kivg7Ol37uMcEzOPkn5wFmLCkO3Qc9XCkAbKbg9i5FWh+iNqwigZFvnxzmN8qIkt2fEDVlIygmoFiFCebiY+er4rXMHgUoy/MMhRN6jfSLE4kWzyyQPiSylW82mJ58TSjr0JGdBQ5MAwmgnLbo5xAVikJNr+rfLdokvLWGFVHH+fs9eAofGPVt9VXZmyzRW1MQVKk7wbduJ3i6nW14QIMInXsJ/LRSihRwyJ3Z0PTQQeNeU0uU+x0Yp5zdsOFbnm8OV5VZ+G+LIq1VPorw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: loki-credentials
      namespace: loki
