apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-manifests
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://github.com/waaghals/cluster-management.git
    targetRevision: main
    path: 'crossplane/manifests'
    plugin:
      name: argocd-vault-plugin-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
