apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.8.1
    chart: crossplane
    helm:
      values: |
        provider:
          packages:
            - crossplane/provider-gcp:master
            - crossplane/provider-helm:master
            - crossplane/provider-kubernetes:master
            - upbound/platform-ref-multi-k8s:master
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
