apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: argocd.management.waaghals.dev
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  name: https
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - argocd.management.waaghals.dev
      secretName: argocd-cert
