apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - repositories/cluster-management.yaml
  - repositories/external-dns-repository.yaml
  - repositories/fluent-repository.yaml
  - repositories/grafana-repository.yaml
  - repositories/jetstack-repository.yaml
  - repositories/nginx-repository.yaml
  - repositories/prometheus-community-repository.yaml
  - repositories/sealed-secrets-repository.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.12/manifests/install.yaml
  - clusters/management-cluster.yaml
  - projects/cluster-management.yaml
  - projects/continous-deployment.yaml
  - projects/ingress.yaml
  - projects/monitoring.yaml
  - projects/security.yaml
  - applications/root.yaml
  - ingress.yaml
  - service-monitor.yaml

patchesStrategicMerge:
  - patch-dashboard.yaml
  - patch-config.yaml

configMapGenerator:
  - name: grafana-dashboard
    files:
      - dashboard.json
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - reposerver.log.format=json
      - server.log.format=json
      - controller.log.format=json

generatorOptions:
   disableNameSuffixHash: true
