apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mimir-credentials
  namespace: prometheus-operator
spec:
  encryptedData:
    password: AgB3YkcCzn9hRA11klksuYZgwIeJbhKnJ1UGr0lRHVEsDYgNepYZFWR3LoExA1P9QRP29jE/3D4V83Zbz35N7hd289gcr21Id5xrj3X8LoSYv9sqjJT6JF/JUmdL619q6DsKo+JqK7Li1CmV6u22jVw7vJNOULM2wy+nYZreg0b3vE00SDupE6hdZz3oJBNmfMXlQ/X5LvdHpMI8ChmBVi9hPWIn07w110+gPV9oAh5v6zfffO9Djy2ed2BwEJ/gsQuO71CmfVIOYd3JvY6fqpWEWOjUvwN7qoa+j8/jRiEI6nnQE0G6NMaknYLFkuvKwdN+WZMI3i/iByEAMR9M8jTto3fTJ5BYw0TfZAYEYkLqjuvlz0JFMjcLeDJUYiXklNyT2WfVKcvsGEnODNXu2VgkvOrPF+GJlfh/AUhbx0V7Fknk34e+CFcJieY6yrXTqXyehXq82yPgbnRyyHOWLsVobOZftvZYp9SHcu+WOKhh8NVwahWHE1omIel64zu0XEyqleWDiP8E1tXO3KaVPk0cpBOSdqlu3nlafo3wh8AKvtzD+8D0hfIdZW2gaUt50bOpDgpmXlhO91kM/s3gu4SRt79yAgJKHebf5wv87NHqjJNENHVn6jgXkGuh0467y4hN6wZ6j7kjKtQlNlvET/OazzbmxVWViZ6TBfRLKEJickzVEL1vssmCP6p8DSeoeoYgpaisQD1tb79Ape0fdO4/tiy9sIDMGI8=
    username: AgBX2+enqkHVSZBR3TJp5pFbxPDuz/mW2GuaVQ9CEqZs6sJAERzNErtteU9OGYT6xLuX44GdTzBeNCcxVQfDTa98+vGYKLMY0aGQ8OHL2xbwT4BeYDkLaLC5+KOkcoJNnM26dbox15Bu65zztEn0Ng7nCp3X/QGOrMMeXHsLFgf01fZkIaVBkLl2ZnuRqWIsJMl8ZrPZ0nXlc5Sph3+bH9dWbcp4I4SjWL+Gilxa+FMSFavg0FZEQrKn//Yyz5fZ3WW3+E86uGObTjq77VbM43iSDqsfCwJBN08AObsvD1ZKzWUAWp2DgFP4OVwHgKbDgbymecomw7yG3rWTN4sQo2JZXiWcxA4UZOpc6pdB1IwxrQS/1vkYsoG/mgDTBQNWrJq+a4yqx1AmgmJblzsH+FesyLdew8kqHBr7dphg4pxOy0EaUCpsWP/fTf24hqJCxjIwOxDXbGBHw9xUYaXeELhFcb/yvsEkounGT+4T1sZlxUBM47kyJJVGX9y1qcjslHxSz3YdGd7cRk3SnYAKtYMa+JRaY6S0DBFfEPsKR6/v8crLqMZmjMPZ/IthGYWKpQyS0oXfN/gEjThhYD1Ffr46B9NSJSF7DGBp/SvFHcqjUT4dWtutvKV5QCjY/gXK24fu4D9edJyQqUgwF92IeowkuQkWeqAB5Zn+6GzId+VbZjVXgzGKIe7DnU/Q12j0W3xgoNQ3sg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mimir-credentials
      namespace: prometheus-operator

