apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
spec:
  generators:
    - git:
        repoURL: 'https://github.com/waaghals/cluster-management.git'
        revision: main
        # TODO fix pattern
        directories:
          - path: 'argocd'
          - path: 'cert-manager'
          - path: 'external-dns'
          - path: 'fluent-bit'
          - path: 'grafana'
          - path: 'loki'
          - path: 'mimir'
          - path: 'nginx-ingress'
          - path: 'prometheus-operator'
          - path: 'sealed-secrets'
  template:
    metadata:
      name: 'meta-{{path.basename}}'
    spec:
      project: continuous-deployment
      source:
        repoURL: https://github.com/waaghals/cluster-management.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
