apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.44.0
    chart: consul
    helm:
      parameters:
        - name: "global.name"
          value: "consul"
        - name: "global.logJSON"
          value: "true"
        - name: "server.replicas"
          value: "1"
        - name: "server.bootstrapExpect"
          value: "1"
        - name: "server.disruptionBudget.maxUnavailable"
          value: "0"
  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
