apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.44.0
    chart: consul
    helm:
      values: |
        global:
          name: consul
          logJSON: true
        server:
          replicas: 1
          bootstrapExpect: 1
          disruptionBudget:
            maxUnavailable: 0
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
