apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.20.1
    chart: vault
    helm:
      parameters:
        - name: "global.enabled"
          value: "true"
        - name: "injector.enabled"
          value: "false"
        - name: "ingress.enabled"
          value: "true"
        - name: "ha.enabled"
          value: "true"
        - name: "ui.enabled"
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
