apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: security
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.20.1
    chart: vault
    helm:
      values: |
        global:
          enabled: true
        injector:
          enabled: false
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - vault.management.waaghals.dev
          tls:
            - secretName: vault-cert
              hosts:
                - vault.management.waaghals.dev
        ha:
          enabled: true
        ui:
          enabled: true
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
