apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
    - resources-finalizer.argo-cd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: cluster-management
  source:
    path: argo-cd
    repoURL: https://github.com/waaghals/cluster-management.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
