apiVersion: v1
kind: Secret
metadata:
  name: bitname-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.bitnami.com/bitnami
  name: bitnami
  type: helm
