apiVersion: v1
kind: Secret
metadata:
  name: external-dns-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kubernetes-sigs.github.io/external-dns
  name: external-dns
  type: helm
