apiVersion: v1
kind: Secret
metadata:
  name: grafana-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://grafana.github.io/helm-charts
  name: grafana
  type: helm
