apiVersion: v1
kind: Secret
metadata:
  name: hashicorp-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://helm.releases.hashicorp.com
  name: hashicorp
  type: helm
