apiVersion: v1
kind: Secret
metadata:
  name: nginx-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kubernetes.github.io/ingress-nginx
  name: nginx
  type: helm
