apiVersion: v1
data:
  tls.crt: <path:secret/data/linkerd/trust-anchor#crt | base64encode>
  tls.key: <path:secret/data/linkerd/trust-anchor#key | base64encode>
kind: Secret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: linkerd
type: kubernetes.io/tls
