apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns-secret
  namespace: argocd
spec:
  generators:
    - clusters: {} # All clusters
  template:
    metadata:
      name: external-dns-secret-{{name}}
    spec:
      project: cluster-management
      source:
        repoURL: https://github.com/waaghals/cluster-management.git
        targetRevision: main
        path: 'external-dns/application'
        plugin:
          name: argocd-vault-plugin
      destination:
        server: '{{server}}'
        namespace: 'external-dns'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

