apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns-manifests
  namespace: argocd
spec:
  generators:
    - clusters: {} # All clusters
  template:
    metadata:
      name: external-dns-manifests-{{name}}
    spec:
      project: ingress
      source:
        repoURL: https://github.com/waaghals/cluster-management.git
        targetRevision: main
        path: 'external-dns/manifests'
      destination:
        server: '{{server}}'
        namespace: 'external-dns'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

