apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-manifests
  namespace: argocd
spec:
  generators:
    - clusters: {} # All clusters
  template:
    metadata:
      name: cert-manager-manifests-{{name}}
    spec:
      project: ingress
      source:
        repoURL: https://github.com/waaghals/cluster-management.git
        targetRevision: main
        path: 'cert-manager/manifests'
      destination:
        server: '{{server}}'
        namespace: 'cert-manager'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
