# Special type of cluster, which is local
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
    type: management
  name: management
type: Opaque
stringData:
  config: "{\"tlsClientConfig\":{\"insecure\":false}}"
  name: management
  server: https://kubernetes.default.svc
